// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBack.Models;

namespace WebBack.Migrations
{
    [DbContext(typeof(PoslasticaraContext))]
    [Migration("20210813102656_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBack.Models.Porudzbina", b =>
                {
                    b.Property<int>("IDPorudzbine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDPorudzbine")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Deserti")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Deserti");

                    b.Property<string>("Pice")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Pice");

                    b.Property<int?>("PoslasticaraID")
                        .HasColumnType("int");

                    b.HasKey("IDPorudzbine");

                    b.HasIndex("PoslasticaraID");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("WebBack.Models.Poslasticara", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresa");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("MaxLjudi")
                        .HasColumnType("int")
                        .HasColumnName("MaxLjudi");

                    b.Property<int>("MaxLokala")
                        .HasColumnType("int")
                        .HasColumnName("MaxLokala");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Poslasticara");
                });

            modelBuilder.Entity("WebBack.Models.Sto", b =>
                {
                    b.Property<int>("IDStola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDStola")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojStola")
                        .HasColumnType("int")
                        .HasColumnName("BrojStola");

                    b.Property<string>("Ime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Ime");

                    b.Property<int>("KapacitetStola")
                        .HasColumnType("int")
                        .HasColumnName("KapacitetStola");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MaxKapacitet");

                    b.Property<int?>("PoslasticaraID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Prezime");

                    b.Property<string>("Stanje")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Stanje");

                    b.HasKey("IDStola");

                    b.HasIndex("PoslasticaraID");

                    b.ToTable("Sto");
                });

            modelBuilder.Entity("WebBack.Models.Porudzbina", b =>
                {
                    b.HasOne("WebBack.Models.Poslasticara", "Poslasticara")
                        .WithMany("Porudzbine")
                        .HasForeignKey("PoslasticaraID");

                    b.Navigation("Poslasticara");
                });

            modelBuilder.Entity("WebBack.Models.Sto", b =>
                {
                    b.HasOne("WebBack.Models.Poslasticara", "Poslasticara")
                        .WithMany("Stolovi")
                        .HasForeignKey("PoslasticaraID");

                    b.Navigation("Poslasticara");
                });

            modelBuilder.Entity("WebBack.Models.Poslasticara", b =>
                {
                    b.Navigation("Porudzbine");

                    b.Navigation("Stolovi");
                });
#pragma warning restore 612, 618
        }
    }
}
